version: '3.8'

services:
  flask_app:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=your_neo4j_password
      - FLASK_ENV=development
    depends_on:
      neo4j:
        condition: service_healthy # Wait for neo4j to be ready
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  neo4j:
    image: 'neo4j:latest'
    ports:
      - '7474:7474'
      - '7687:7687'
    environment:
      NEO4J_AUTH: 'neo4j/your_neo4j_password'
    healthcheck:
      test: cypher-shell --username neo4j --password your_neo4j_password 'MATCH (n) RETURN COUNT(n);' # Checks if neo4j server is up and running
      interval: 5s
      timeout: 5s
      retries: 5
